In [11]:
import sys
sys.path.append("../data/")
sys.path.append("../misc/")
sys.path.append("../models/")
sys.path.append("../preprocessing/")
sys.path.append("../tools/")


import json
import random
import numpy as np
from PIL import Image
from plot_utils import PlotMaps, PlotHeatmaps

In [12]:
data_dir = f'../data/HuPR/single_{random.randint(1, 10)}'

hori_bin = data_dir + '/hori/adc_data.bin'
vert_bin = data_dir + '/vert/adc_data.bin'

# open the binary file
hori_data = np.fromfile(hori_bin, dtype=np.int16)
vert_data = np.fromfile(vert_bin, dtype=np.int16)

In [17]:
print(hori_data, hori_data.shape)
print(vert_data, vert_data.shape)

[24 62 61 ... 62 53 60] (235929600,)
[ 32   4 -93 ... 177  -8 134] (235929600,)


In [15]:
vert_data

array([ 32,   4, -93, ..., 177,  -8, 134], dtype=int16)